# Generated by Django 6.0.1 on 2026-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_comentario_bloqueado_por_comentario_fecha_bloqueo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre de la habilidad'),
        ),
        migrations.AddIndex(
            model_name='habilidad',
            index=models.Index(fields=['nombre'], name='src_habilid_nombre_2414ba_idx'),
        ),
        migrations.AddIndex(
            model_name='habilidad',
            index=models.Index(fields=['profesional', 'nombre'], name='src_habilid_profesi_ecef54_idx'),
        ),
    ]
