# Generated by Django 6.0.1 on 2026-03-19 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_habilidad_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_postulacion', 'Nueva postulación'), ('postulacion_aceptada', 'Postulación aceptada'), ('postulacion_rechazada', 'Postulación rechazada'), ('nuevo_seguidor', 'Nuevo seguidor'), ('nuevo_mensaje', 'Nuevo mensaje'), ('like_publicacion', 'Like en publicación'), ('comentario_publicacion', 'Comentario en publicación'), ('respuesta_comentario', 'Respuesta a comentario')], max_length=30, verbose_name='Tipo de notificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL de destino')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['destinatario', 'leida', 'activa'], name='src_notific_destina_278a7c_idx'), models.Index(fields=['-fecha_creacion'], name='src_notific_fecha_c_8d599c_idx')],
            },
        ),
    ]
