# Generated by Django 6.0.1 on 2026-03-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de guardado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas personales')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardado_por', to='src.ofertaempleo', verbose_name='Oferta de empleo')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleos_guardados', to='src.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Empleo guardado',
                'verbose_name_plural': 'Empleos guardados',
                'ordering': ['-fecha_guardado'],
                'indexes': [models.Index(fields=['profesional', '-fecha_guardado'], name='src_empleog_profesi_b2181b_idx')],
                'unique_together': {('profesional', 'oferta')},
            },
        ),
    ]
