# Generated by Django 6.0.1 on 2026-03-02 19:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/', verbose_name='Foto de perfil')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('tipo_usuario', models.CharField(blank=True, choices=[('profesional', 'Profesional'), ('empresa', 'Empresa')], max_length=20, null=True, verbose_name='Tipo de usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_bloqueadas', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por')),
                ('participante_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Participante 1')),
                ('participante_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Participante 2')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('participante_1', 'participante_2')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
                ('tipo_empresa', models.CharField(choices=[('startup', 'Startup'), ('pyme', 'PYME'), ('corporacion', 'Corporación'), ('ong', 'ONG'), ('gobierno', 'Gobierno'), ('educacion', 'Institución Educativa')], max_length=20, verbose_name='Tipo de empresa')),
                ('descripcion_breve', models.TextField(blank=True, help_text='Descripción corta de la empresa', verbose_name='Descripción breve')),
                ('descripcion_completa', models.TextField(blank=True, help_text='Información detallada sobre la empresa', verbose_name='Descripción completa')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector/Industria')),
                ('tamano', models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-500', '201-500 empleados'), ('501-1000', '501-1000 empleados'), ('1000+', 'Más de 1000 empleados')], max_length=20, verbose_name='Tamaño de la empresa')),
                ('ano_fundacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del mensaje')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/', verbose_name='Archivo adjunto')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='src.conversacion', verbose_name='Conversación')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción del puesto')),
                ('requisitos', models.TextField(help_text='Habilidades y experiencia requerida', verbose_name='Requisitos')),
                ('responsabilidades', models.TextField(blank=True, verbose_name='Responsabilidades')),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20, verbose_name='Nivel de experiencia')),
                ('tipo_empleo', models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('medio_tiempo', 'Medio tiempo'), ('freelance', 'Freelance'), ('pasantia', 'Pasantía'), ('temporal', 'Temporal')], max_length=20, verbose_name='Tipo de empleo')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Modalidad')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mínimo')),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario máximo')),
                ('mostrar_salario', models.BooleanField(default=True, verbose_name='Mostrar salario públicamente')),
                ('activa', models.BooleanField(default=True, verbose_name='Oferta activa')),
                ('destacada', models.BooleanField(default=False, verbose_name='Oferta destacada')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('vistas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de vistas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='src.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Oferta de Empleo',
                'verbose_name_plural': 'Ofertas de Empleo',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], default='prefiero_no_decir', max_length=20, verbose_name='Género')),
                ('descripcion_personal', models.TextField(blank=True, help_text='Descripción profesional breve', verbose_name='Acerca de mí')),
                ('titulo_actual', models.CharField(blank=True, help_text='Ej: Estudiante de Ingeniería en Computación', max_length=200, verbose_name='Título/Cargo actual')),
                ('color_favorito', models.CharField(blank=True, max_length=50, verbose_name='Color favorito')),
                ('libro_favorito', models.CharField(blank=True, max_length=200, verbose_name='Libro favorito')),
                ('musica_favorita', models.CharField(blank=True, max_length=200, verbose_name='Música favorita')),
                ('videojuegos_favoritos', models.CharField(blank=True, max_length=200, verbose_name='Videojuegos favoritos')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web personal')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('tipo_empleo', models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('medio_tiempo', 'Medio tiempo'), ('freelance', 'Freelance'), ('pasantia', 'Pasantía'), ('practicas', 'Prácticas')], max_length=50, verbose_name='Tipo de empleo')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=50, verbose_name='Modalidad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('trabajo_actual', models.BooleanField(default=False, verbose_name='Trabajo actual')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de responsabilidades')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='src.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('titulo', models.CharField(help_text='Ej: Ingeniería en Computación', max_length=200, verbose_name='Título/Grado')),
                ('campo_estudio', models.CharField(blank=True, max_length=200, verbose_name='Campo de estudio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si está en curso', null=True, verbose_name='Fecha de finalización')),
                ('en_curso', models.BooleanField(default=False, verbose_name='Actualmente cursando')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='src.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/imagenes/', verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to='publicaciones/videos/', verbose_name='Video')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nivel', models.IntegerField(default=0, verbose_name='Nivel de anidación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='src.comentario', verbose_name='Comentario padre')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='src.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('entrevista', 'En entrevista'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('retirada', 'Retirada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('habilidades_tecnicas', models.TextField(help_text='Lista de habilidades separadas por comas', verbose_name='Habilidades técnicas')),
                ('anos_experiencia', models.PositiveIntegerField(verbose_name='Años de experiencia')),
                ('nivel_habilidad', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], max_length=20, verbose_name='Nivel de habilidad')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('curriculum', models.FileField(upload_to='postulaciones/cvs/', verbose_name='Currículum')),
                ('carta_presentacion', models.TextField(blank=True, verbose_name='Carta de presentación')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('guardada', models.BooleanField(default=False, verbose_name='Oferta guardada')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='src.ofertaempleo', verbose_name='Oferta')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='src.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
                'unique_together': {('profesional', 'oferta')},
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la habilidad')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='intermedio', max_length=20, verbose_name='Nivel')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregada')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='src.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('profesional', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='src.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de seguimiento')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL, verbose_name='Seguido')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siguiendo', to=settings.AUTH_USER_MODEL, verbose_name='Seguidor')),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'Seguidores',
                'ordering': ['-fecha_seguimiento'],
                'unique_together': {('seguidor', 'seguido')},
            },
        ),
    ]
