# Generated by Django 6.0.1 on 2026-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios/imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comentarios/videos/', verbose_name='Video'),
        ),
    ]
