# Generated by Django 6.0.1 on 2026-03-05 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_comentario_imagen_comentario_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='bloqueado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_bloqueados', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de bloqueo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='razon_bloqueo',
            field=models.TextField(blank=True, verbose_name='Razón del bloqueo'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='bloqueado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_bloqueadas', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de bloqueo'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='razon_bloqueo',
            field=models.TextField(blank=True, verbose_name='Razón del bloqueo'),
        ),
    ]
